validation
AndriyIvanenko/nodejs-homework-rest-api pull request #1
Opened 2023-01-08 11:02 UTC by AndriyIvanenko

2023-01-08 18:26 UTC, KhYulian commented on models/contacts.js
> +  const contact = JSON.parse(contacts).filter(
Використовуйте .find()

2023-01-08 18:26 UTC, KhYulian commented on models/contacts.js
> +  if (contacts.length === updatedContacts.length) {
оператори порівняння і так повертають булеан

2023-01-08 18:27 UTC, KhYulian commented on routes/api/contacts.js
> +    phone: Joi.string()
винесіть   const schema  в окремий файл

2023-01-08 18:27 UTC, KhYulian commented on routes/api/contacts.js
> +        tlds: { allow: ["com", "net"] },
теж винеість   const schema

2023-01-08 18:27 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-08 18:29 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення

2023-01-08 22:16 UTC, AndriyIvanenko commented on models/contacts.js
> +  const contact = JSON.parse(contacts).filter(
виправив

2023-01-08 22:16 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +    phone: Joi.string()
виправив

2023-01-08 22:16 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +        tlds: { allow: ["com", "net"] },
виправив

2023-01-08 22:27 UTC, AndriyIvanenko commented on models/contacts.js
> +  if (contacts.length === updatedContacts.length) {
переніс запис у файл в if else, щоби не переписувати файл у випадку, коли не знайдено контакт за id

2023-01-09 12:02 UTC, KhYulian approved these changes
:ok_hand:

2023-01-09 12:03 UTC, merged