Hw03 mongodb
AndriyIvanenko/nodejs-homework-rest-api pull request #2
Opened 2023-01-12 23:50 UTC by AndriyIvanenko

2023-01-13 07:24 UTC, KhYulian commented on models/db-connection.js
> +main();
Можна використати IIFE

2023-01-13 07:25 UTC, KhYulian commented on routes/api/contacts.js
> +  //
//  - ці коменти непотрібні - видаліть

2023-01-13 07:26 UTC, KhYulian commented on routes/api/contacts.js
> +    res.status(400).json({ message: postSchema.validate(req.body).error.message });
Винесіть валідацію в окрему middleware, яка спрацьовуватиме перед контроллером

2023-01-13 07:27 UTC, KhYulian commented on routes/api/contacts.js
> +  }
теж можна винести в окрему middleware, або, хоча б винести результат перевірки mongoose.Types.ObjectId.isValid(req.params.contactId) у змінну для кращої читабельності

2023-01-13 07:28 UTC, KhYulian commented on routes/api/contacts.js
> +  if (req.body.name || req.body.email || req.body.phone) {
для таких перевірок у вас є Joi

2023-01-13 07:28 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-13 07:29 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення

2023-01-13 19:01 UTC, AndriyIvanenko commented on models/db-connection.js
> +main();
поправив

2023-01-13 19:01 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +  //
видалив

2023-01-13 19:01 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +    res.status(400).json({ message: postSchema.validate(req.body).error.message });
виконано

2023-01-13 19:01 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +  }
виконано

2023-01-13 19:02 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +  if (req.body.name || req.body.email || req.body.phone) {
переніс перевірку у відповідну схему

2023-01-13 19:10 UTC, KhYulian commented on routes/api/contacts.js
> +});
Дуже сумнівна практика. Буде працювати доки у вас тільки контакти

2023-01-13 19:11 UTC, KhYulian requested changes
Потрібне доопарцювання

2023-01-13 19:11 UTC, KhYulian commented on routes/api/contacts.js
> +router.post('/', async (req, res, next) => {
Малося на увазі додати middleware тут router.post('/', async (req, res, next) => {// validationMiddleware}, async (req, res, next) => {// controller})

2023-01-13 22:16 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +router.post('/', async (req, res, next) => {
переписав згідно рекомендації

2023-01-13 22:16 UTC, AndriyIvanenko commented on routes/api/contacts.js
> +});
видалив

2023-01-14 06:34 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-14 06:34 UTC, merged